import { EvolutionStage, EvolutionStageId, Skin, TapStyle } from '../types';

export const EVOLUTION_STAGES: EvolutionStage[] = [
  {
    id: 'COMMON_SMALL',
    name: 'Ajo Común Pequeño',
    rank: 'COMMON',
    size: 'SMALL',
    order: 1,
    requiredXp: 0,
    requiredTaps: 0,
    requiredGarlicTeeth: 0,
    requiredQuests: 0,
    description: 'Un pequeño diente de ajo humilde que recién empieza su viaje.',
    celebrationMessage: '¡Bienvenido al mundo de AJO! Tu pequeño diente de ajo está listo para cosechar.',
    auraColor: 'rgba(16, 185, 129, 0.15)',
    themeGradient: 'from-emerald-500 to-green-600',
    badgeIcon: '🧄',
    garlicBodyStartColor: '#FFFFFF',
    garlicBodyEndColor: '#E2D7C2',
    strokeColor: '#D6C5A8',
  },
  {
    id: 'COMMON_BIG',
    name: 'Ajo Común Grande',
    rank: 'COMMON',
    size: 'BIG',
    order: 2,
    requiredXp: 200,
    requiredTaps: 150,
    requiredGarlicTeeth: 10,
    requiredQuests: 1,
    description: 'Ha comido buena tierra y ahora es un ajo robusto y saludable.',
    celebrationMessage: '¡EL AJO HA CRECIDO! Ha doblado su volumen y fortaleza.',
    auraColor: 'rgba(16, 185, 129, 0.35)',
    themeGradient: 'from-emerald-400 to-teal-600',
    badgeIcon: '🌿',
    garlicBodyStartColor: '#FFFFFF',
    garlicBodyEndColor: '#D3C4A5',
    strokeColor: '#C4B18E',
  },
  {
    id: 'BRONZE_SMALL',
    name: 'Ajo de Bronce Pequeño',
    rank: 'BRONZE',
    size: 'SMALL',
    order: 3,
    requiredXp: 600,
    requiredTaps: 500,
    requiredGarlicTeeth: 30,
    requiredQuests: 2,
    description: 'Sus capas exteriores han adquirido una pátina metálica de bronce brillante.',
    celebrationMessage: '¡TU AJO HA DESCUBIERTO EL PODER DEL BRONCE! Ahora brilla como una medalla de bronce.',
    auraColor: 'rgba(217, 119, 6, 0.35)',
    themeGradient: 'from-amber-600 to-orange-700',
    badgeIcon: '🥉',
    garlicBodyStartColor: '#FDE68A',
    garlicBodyEndColor: '#B45309',
    strokeColor: '#92400E',
  },
  {
    id: 'BRONZE_BIG',
    name: 'Ajo de Bronce Grande',
    rank: 'BRONZE',
    size: 'BIG',
    order: 4,
    requiredXp: 1200,
    requiredTaps: 1200,
    requiredGarlicTeeth: 60,
    requiredQuests: 3,
    description: 'Un imponente bloque de bronce resistente a cualquier cocinero.',
    celebrationMessage: '¡ESTO YA NO ES UN AJO COMÚN! El Ajo de Bronce Grande domina el cultivo.',
    auraColor: 'rgba(245, 158, 11, 0.45)',
    themeGradient: 'from-amber-500 to-yellow-600',
    badgeIcon: '🥉✨',
    garlicBodyStartColor: '#FEF08A',
    garlicBodyEndColor: '#D97706',
    strokeColor: '#B45309',
  },
  {
    id: 'SILVER_SMALL',
    name: 'Ajo de Plata Pequeño',
    rank: 'SILVER',
    size: 'SMALL',
    order: 5,
    requiredXp: 2500,
    requiredTaps: 2500,
    requiredGarlicTeeth: 120,
    requiredQuests: 4,
    description: 'Refleja la luz de la luna con su deslumbrante armadura de plata pura.',
    celebrationMessage: '¡EL AJO HA ALCANZADO LA ETAPA DE PLATA! Su aroma es legendario.',
    auraColor: 'rgba(148, 163, 184, 0.45)',
    themeGradient: 'from-slate-300 to-slate-500',
    badgeIcon: '🥈',
    garlicBodyStartColor: '#F8FAFC',
    garlicBodyEndColor: '#94A3B8',
    strokeColor: '#64748B',
  },
  {
    id: 'SILVER_BIG',
    name: 'Ajo de Plata Grande',
    rank: 'SILVER',
    size: 'BIG',
    order: 6,
    requiredXp: 5000,
    requiredTaps: 5000,
    requiredGarlicTeeth: 200,
    requiredQuests: 5,
    description: 'Una masa plateada formidable capaz de repeler a los vampiros más antiguos.',
    celebrationMessage: '¡PLATA PURA EN SU MÁXIMO ESPLENDOR! Tu ajo inspira respeto absoluto.',
    auraColor: 'rgba(203, 213, 225, 0.55)',
    themeGradient: 'from-slate-200 to-blue-400',
    badgeIcon: '🥈✨',
    garlicBodyStartColor: '#FFFFFF',
    garlicBodyEndColor: '#CBD5E1',
    strokeColor: '#475569',
  },
  {
    id: 'GOLD_SMALL',
    name: 'Ajo de Oro Pequeño',
    rank: 'GOLD',
    size: 'SMALL',
    order: 7,
    requiredXp: 10000,
    requiredTaps: 10000,
    requiredGarlicTeeth: 350,
    requiredQuests: 6,
    description: 'Fundido en oro macizo de 24 quilates, resplandece en cualquier cocina.',
    celebrationMessage: '¡ÉPICO! ¡TU AJO AHORA ES DE ORO! Los reyes sueñan con esta cosecha.',
    auraColor: 'rgba(234, 179, 8, 0.55)',
    themeGradient: 'from-yellow-400 to-amber-500',
    badgeIcon: '🥇',
    garlicBodyStartColor: '#FEF08A',
    garlicBodyEndColor: '#EAB308',
    strokeColor: '#CA8A04',
  },
  {
    id: 'GOLD_BIG',
    name: 'Ajo de Oro Grande',
    rank: 'GOLD',
    size: 'BIG',
    order: 8,
    requiredXp: 20000,
    requiredTaps: 20000,
    requiredGarlicTeeth: 500,
    requiredQuests: 7,
    description: 'Un monumento de oro colosal que eclipsa al sol con su brillo deslumbrante.',
    celebrationMessage: '¡ORO COLOSAL! El Ajo de Oro Grande es una leyenda de la agricultura.',
    auraColor: 'rgba(250, 204, 21, 0.65)',
    themeGradient: 'from-yellow-300 to-amber-600',
    badgeIcon: '🥇👑',
    garlicBodyStartColor: '#FEF9C3',
    garlicBodyEndColor: '#D97706',
    strokeColor: '#A16207',
  },
  {
    id: 'PLATINUM_SMALL',
    name: 'Ajo de Platino Pequeño',
    rank: 'PLATINUM',
    size: 'SMALL',
    order: 9,
    requiredXp: 40000,
    requiredTaps: 40000,
    requiredGarlicTeeth: 800,
    requiredQuests: 8,
    description: 'Compuesto por elementos rarísimos de las profundidades estelares.',
    celebrationMessage: '¡PLATINO DESBLOQUEADO! Has trascendido el metal común.',
    auraColor: 'rgba(168, 85, 247, 0.55)',
    themeGradient: 'from-purple-400 to-indigo-600',
    badgeIcon: '💎',
    garlicBodyStartColor: '#F3E8FF',
    garlicBodyEndColor: '#C084FC',
    strokeColor: '#7E22CE',
  },
  {
    id: 'PLATINUM_BIG',
    name: 'Ajo de Platino Grande',
    rank: 'PLATINUM',
    size: 'BIG',
    order: 10,
    requiredXp: 75000,
    requiredTaps: 75000,
    requiredGarlicTeeth: 1200,
    requiredQuests: 9,
    description: 'Un titan de platino cósmico que altera la gravedad a su alrededor.',
    celebrationMessage: '¡TITÁN DE PLATINO! Tu Ajo genera su propio campo gravitatorio.',
    auraColor: 'rgba(192, 132, 252, 0.7)',
    themeGradient: 'from-purple-300 to-pink-600',
    badgeIcon: '💎⚡',
    garlicBodyStartColor: '#FAF5FF',
    garlicBodyEndColor: '#A855F7',
    strokeColor: '#6B21A8',
  },
  {
    id: 'DIAMOND_SMALL',
    name: 'Ajo de Diamante Pequeño',
    rank: 'DIAMOND',
    size: 'SMALL',
    order: 11,
    requiredXp: 150000,
    requiredTaps: 150000,
    requiredGarlicTeeth: 2000,
    requiredQuests: 10,
    description: 'Cristalizado bajo presión extrema en el núcleo de la galaxia del Ajo.',
    celebrationMessage: '¡DIAMANTE PURO! Tu Ajo refracta destellos celestiales.',
    auraColor: 'rgba(56, 189, 248, 0.65)',
    themeGradient: 'from-cyan-400 to-blue-600',
    badgeIcon: '💎✨',
    garlicBodyStartColor: '#E0F2FE',
    garlicBodyEndColor: '#38BDF8',
    strokeColor: '#0284C7',
  },
  {
    id: 'DIAMOND_BIG',
    name: 'Ajo Diamante Supremo',
    rank: 'DIAMOND',
    size: 'BIG',
    order: 12,
    requiredXp: 300000,
    requiredTaps: 300000,
    requiredGarlicTeeth: 3500,
    requiredQuests: 12,
    description: 'La forma máxima del universo AJO. Indestructible, divino e inmortal.',
    celebrationMessage: '¡DIAMANTE SUPREMO ALCANZADO! Has conquistado el universo AJO COIN.',
    auraColor: 'rgba(14, 165, 233, 0.85)',
    themeGradient: 'from-cyan-300 via-sky-400 to-indigo-600',
    badgeIcon: '👑💎🔥',
    garlicBodyStartColor: '#F0F9FF',
    garlicBodyEndColor: '#0EA5E9',
    strokeColor: '#0369A1',
  },
];

export const SKINS_CATALOG: Skin[] = [
  {
    id: 'DEFAULT',
    name: 'Ajo Natural',
    description: 'El clásico ajo sin accesorios. Humilde, fresco y oloroso.',
    priceGarlicTeeth: 0,
    icon: '🧄',
    tag: 'Básico',
    headgearEmoji: '',
  },
  {
    id: 'NINJA',
    name: 'Ninja Ajo',
    description: 'Silencioso pero letal. Ataca desde las sombras de la ensalada.',
    priceGarlicTeeth: 15,
    icon: '🥷',
    tag: 'Sigilo',
    headgearEmoji: '🥷',
  },
  {
    id: 'KING',
    name: 'King Ajo',
    description: 'Lleva una corona dorada de soberano de la cocina.',
    priceGarlicTeeth: 30,
    icon: '👑',
    tag: 'Realeza',
    headgearEmoji: '👑',
  },
  {
    id: 'ROBOT',
    name: 'Robot Ajo',
    description: 'Mejorado cibernéticamente con circuitos de silicio y ajo.',
    priceGarlicTeeth: 50,
    icon: '🤖',
    tag: 'Futurista',
    headgearEmoji: '🤖',
  },
  {
    id: 'FIRE',
    name: 'Fire Ajo',
    description: 'Envuelto en llamas ardientes. ¡Demasiado picante!',
    priceGarlicTeeth: 75,
    icon: '🔥',
    tag: 'Picante',
    headgearEmoji: '🔥',
  },
  {
    id: 'ALIEN',
    name: 'Alien Ajo',
    description: 'Llegado en un OVNI desde la nebulosa Allium.',
    priceGarlicTeeth: 100,
    icon: '👽',
    tag: 'Cósmico',
    headgearEmoji: '👽',
  },
  {
    id: 'DEAD',
    name: 'Dead / Zombie Ajo',
    description: 'Ha vuelto de la compostera con hambre de victorias.',
    priceGarlicTeeth: 150,
    icon: '💀',
    tag: 'Zombi',
    headgearEmoji: '💀',
  },
  {
    id: 'RICH',
    name: 'Rich / Top Hatted Ajo',
    description: 'Lleva sombrero de copa y monoculo. Cultivador millonario.',
    priceGarlicTeeth: 250,
    icon: '🎩',
    tag: 'Lujo',
    headgearEmoji: '🎩',
  },
];

export const TAP_STYLES_CATALOG: TapStyle[] = [
  {
    id: 'NORMAL',
    name: 'Puño Normal',
    description: 'El golpe clásico del ajo. Simple pero efectivo.',
    priceGarlicTeeth: 0,
    color: '#34D399',
    glowColor: 'rgba(52, 211, 153, 0.5)',
    particleEmoji: '💪',
    criticalMultiplier: 1.5,
    criticalChance: 0.05,
    comboMultiplier: 1.0,
    chargeMultiplier: 2.0,
    soundEffect: 'tap',
    unlockRank: 'COMMON',
  },
  {
    id: 'FIRE_PUNCH',
    name: 'Puño de Fuego 🔥',
    description: '¡Golpe ardiente! Quema con cada impacto. Críticos frecuentes.',
    priceGarlicTeeth: 80,
    color: '#F97316',
    glowColor: 'rgba(249, 115, 22, 0.7)',
    particleEmoji: '🔥',
    criticalMultiplier: 2.0,
    criticalChance: 0.15,
    comboMultiplier: 1.3,
    chargeMultiplier: 3.0,
    soundEffect: 'fire',
    unlockRank: 'BRONZE',
  },
  {
    id: 'ICE_STRIKE',
    name: 'Golpe de Hielo ❄️',
    description: 'Congela al objetivo. Slow mo con daño acumulado.',
    priceGarlicTeeth: 100,
    color: '#38BDF8',
    glowColor: 'rgba(56, 189, 248, 0.7)',
    particleEmoji: '❄️',
    criticalMultiplier: 2.5,
    criticalChance: 0.12,
    comboMultiplier: 1.5,
    chargeMultiplier: 3.5,
    soundEffect: 'ice',
    unlockRank: 'BRONZE',
  },
  {
    id: 'THUNDER',
    name: 'Rayo del Ajo ⚡',
    description: 'Impacto eléctrico que encadena combos infinitos.',
    priceGarlicTeeth: 150,
    color: '#FDE047',
    glowColor: 'rgba(253, 224, 71, 0.8)',
    particleEmoji: '⚡',
    criticalMultiplier: 2.0,
    criticalChance: 0.20,
    comboMultiplier: 2.0,
    chargeMultiplier: 3.0,
    soundEffect: 'thunder',
    unlockRank: 'SILVER',
  },
  {
    id: 'SHADOW',
    name: 'Golpe Sombra 🌑',
    description: 'Ataque oscuro que multiplica el daño en silencio.',
    priceGarlicTeeth: 200,
    color: '#A855F7',
    glowColor: 'rgba(168, 85, 247, 0.7)',
    particleEmoji: '🌑',
    criticalMultiplier: 3.0,
    criticalChance: 0.18,
    comboMultiplier: 1.8,
    chargeMultiplier: 4.0,
    soundEffect: 'shadow',
    unlockRank: 'SILVER',
  },
  {
    id: 'KAME_HAME',
    name: 'KAME HAME AJO! ✨',
    description: '¡El ataque definitivo! Carga por 1.5s y libera poder devastador.',
    priceGarlicTeeth: 350,
    color: '#60A5FA',
    glowColor: 'rgba(96, 165, 250, 0.9)',
    particleEmoji: '✨',
    criticalMultiplier: 5.0,
    criticalChance: 0.30,
    comboMultiplier: 2.5,
    chargeMultiplier: 8.0,
    soundEffect: 'kame',
    unlockRank: 'GOLD',
  },
  {
    id: 'COSMIC',
    name: 'Impacto Cósmico 🌌',
    description: 'Fuerza del universo concentrada en el ajo. Daño galáctico.',
    priceGarlicTeeth: 500,
    color: '#C084FC',
    glowColor: 'rgba(192, 132, 252, 0.9)',
    particleEmoji: '🌌',
    criticalMultiplier: 4.0,
    criticalChance: 0.25,
    comboMultiplier: 3.0,
    chargeMultiplier: 6.0,
    soundEffect: 'cosmic',
    unlockRank: 'PLATINUM',
  },
  {
    id: 'DRAGON',
    name: 'Garra del Dragón Ajo 🐉',
    description: '¡El poder del dragón ancestral! Solo los más poderosos lo dominan.',
    priceGarlicTeeth: 800,
    color: '#EF4444',
    glowColor: 'rgba(239, 68, 68, 0.95)',
    particleEmoji: '🐉',
    criticalMultiplier: 6.0,
    criticalChance: 0.35,
    comboMultiplier: 3.5,
    chargeMultiplier: 10.0,
    soundEffect: 'dragon',
    unlockRank: 'DIAMOND',
  },
];

// Helper functions for evolution logic
export function getStageById(stageId: EvolutionStageId): EvolutionStage {
  const found = EVOLUTION_STAGES.find((s) => s.id === stageId);
  return found || EVOLUTION_STAGES[0];
}

export function getNextStage(currentStageId: EvolutionStageId): EvolutionStage | null {
  const currentIndex = EVOLUTION_STAGES.findIndex((s) => s.id === currentStageId);
  if (currentIndex === -1 || currentIndex >= EVOLUTION_STAGES.length - 1) {
    return null;
  }
  return EVOLUTION_STAGES[currentIndex + 1];
}

export function checkEvolutionRequirements(
  currentStageId: EvolutionStageId,
  userStats: { xp: number; totalTaps: number; completedQuestsCount: number },
  userGarlicTeeth: number
): { canEvolve: boolean; nextStage: EvolutionStage | null; missing: string[] } {
  const nextStage = getNextStage(currentStageId);
  if (!nextStage) {
    return { canEvolve: false, nextStage: null, missing: ['Etapa Máxima Alcanzada'] };
  }

  const missing: string[] = [];

  if (userStats.xp < nextStage.requiredXp) {
    missing.push(`Faltan ${nextStage.requiredXp - userStats.xp} XP`);
  }
  if (userStats.totalTaps < nextStage.requiredTaps) {
    missing.push(`Faltan ${nextStage.requiredTaps - userStats.totalTaps} TAPs`);
  }
  if (userGarlicTeeth < nextStage.requiredGarlicTeeth) {
    missing.push(`Faltan ${nextStage.requiredGarlicTeeth - userGarlicTeeth} Garlic Teeth`);
  }
  if (userStats.completedQuestsCount < nextStage.requiredQuests) {
    missing.push(`Faltan ${nextStage.requiredQuests - userStats.completedQuestsCount} Misiones`);
  }

  return {
    canEvolve: missing.length === 0,
    nextStage,
    missing,
  };
}

export interface HitPowerTier {
  level: number;
  bonusPower: number;
  costTeeth: number;
  label: string;
}

export const HIT_POWER_TIERS: HitPowerTier[] = [
  { level: 1, bonusPower: 1.5, costTeeth: 90, label: '+1.5 Poder de Golpe' },
  { level: 2, bonusPower: 2.0, costTeeth: 120, label: '+2.0 Poder de Golpe' },
  { level: 3, bonusPower: 2.5, costTeeth: 200, label: '+2.5 Poder de Golpe' },
  { level: 4, bonusPower: 3.5, costTeeth: 400, label: '+3.5 Poder de Golpe' },
  { level: 5, bonusPower: 5.5, costTeeth: 750, label: '+5.5 Poder de Golpe' },
  { level: 6, bonusPower: 6.0, costTeeth: 1200, label: '+6.0 Poder de Golpe' },
  { level: 7, bonusPower: 7.5, costTeeth: 1800, label: '+7.5 Poder de Golpe (MÁXIMO)' },
];

